name: Ruby

on:
  push:
    branches:
      - develop

  pull_request:

jobs:
  test_gem:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: searchcraft_demo_app_test
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake test
      env:
        DATABASE_URL: postgres://postgres:password@localhost:5432

  test_demo_app:
    runs-on: ubuntu-latest
    name: Rails App ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: searchcraft_demo_app_test
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        working-directory: demo_app

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:password@localhost:5432/searchcraft_demo_app_test
        RAILS_ENV: test
      run: |
        cd demo_app
        bin/rails test:prepare
        bin/rails db:test:prepare
        bin/rails test
        bin/rails test:system
